using IrisSandbox.Connection;
using IrisSandbox.Connection.Interfaces;
using Matrix.LAS.Database.Context;
using Microsoft.Extensions.DependencyInjection;

namespace IrisSandbox
{
    // Migrations Generated by Command: dotnet ef migrations add InitialMigration --context DefaultDbContext
    // Migrations Script Command: dotnet ef migrations script --context DefaultDbContext

    public class Program
    {
        private const string CONNECTION_STRING = "Server=localhost;Port=1972;Namespace=SANDBOX;Password=SYS;User ID=_SYSTEM;";

        public static async Task Main(string[] args)
        {
            CancellationToken cancellationToken = new CancellationToken();

            IDbSandboxConnectionDefault connection = new IrisConnection(CONNECTION_STRING);

            using (DefaultDbContext defaultDbContext = new DefaultDbContext(connection))
            {
                try
                {
                    await defaultDbContext.MigrateAsync(cancellationToken);
                }
                catch (Exception exc)
                {
                    Console.WriteLine(exc.ToString());
                    Console.ReadLine();
                }
            }
        }
    }
}
